name: OpenWRT Github CI
on:
  push:
  watch:
    types: started
  schedule:
    - cron: 0 0 * * */3

jobs:
  deleteOldReleases:
    runs-on: ubuntu-latest
    name: Delete old releases
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        delete_tags: true
        keep_latest: 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Luci:
    runs-on: ubuntu-latest
    name: luci
    needs: [deleteOldReleases]
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Copiler
      uses: Sirherobrine23/Actions-Build-Openwrt@main
      with:
        CONFIG: 'configs/luci.config'
        BRANCH: 'openwrt-19.07'
        P1: 'p1.sh'
        P2: 'p2.sh'
        NGROK_TOKEN: "${{ secrets.NGROK_AUTH }}"

    - name: Upload To Releases
      uses: softprops/action-gh-release@v1
      if: env.UPLOADTORELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Build to ${{ env.DEVICE_NAME }}, Run ID ${{ github.run_id }}
        tag_name: ${{ github.run_id }}-LUCI
        body_path: ${{ env.BODY_PATH }}
        files: ${{ env.FIRMWARE_PATH }}/*

  WG18:
    runs-on: ubuntu-latest
    name: Wireguard with LUCI in 18.06
    needs: [deleteOldReleases]
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Copiler
      uses: Sirherobrine23/Actions-Build-Openwrt@main
      with:
        CONFIG: 'configs/wireguard-with-luci.config'
        BRANCH: 'openwrt-18.06'
        P1: 'p1.sh'
        P2: 'p2.sh'
        NGROK_TOKEN: "${{ secrets.NGROK_AUTH }}"

    - name: Upload To Releases
      uses: softprops/action-gh-release@v1
      if: env.UPLOADTORELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Build to ${{ env.DEVICE_NAME }}, Run ID ${{ github.run_id }}
        tag_name: ${{ github.run_id }}-WG18
        body_path: ${{ env.BODY_PATH }}
        files: ${{ env.FIRMWARE_PATH }}/*
  WG19:
    runs-on: ubuntu-latest
    name: Wireguard with LUCI in 19.07
    needs: [deleteOldReleases]
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Copiler
      uses: Sirherobrine23/Actions-Build-Openwrt@main
      with:
        CONFIG: 'configs/wireguard-with-luci.config'
        BRANCH: 'openwrt-19.07'
        P1: 'p1.sh'
        P2: 'p2.sh'
        NGROK_TOKEN: "${{ secrets.NGROK_AUTH }}"

    - name: Upload To Releases
      uses: softprops/action-gh-release@v1
      if: env.UPLOADTORELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Build to ${{ env.DEVICE_NAME }}, Run ID ${{ github.run_id }}
        tag_name: ${{ github.run_id }}-WG19
        body_path: ${{ env.BODY_PATH }}
        files: ${{ env.FIRMWARE_PATH }}/*

  WG2:
    runs-on: ubuntu-latest
    name: Wireguard without LUCI
    needs: [deleteOldReleases]
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Copiler
      uses: Sirherobrine23/Actions-Build-Openwrt@main
      with:
        CONFIG: 'configs/wireguard-without-luci.config'
        BRANCH: 'openwrt-19.07'
        P1: 'p1.sh'
        P2: 'p2.sh'
        NGROK_TOKEN: "${{ secrets.NGROK_AUTH }}"

    - name: Upload To Releases
      uses: softprops/action-gh-release@v1
      if: env.UPLOADTORELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Build to ${{ env.DEVICE_NAME }}, Run ID ${{ github.run_id }}
        tag_name: ${{ github.run_id }}-WG2
        body_path: ${{ env.BODY_PATH }}
        files: ${{ env.FIRMWARE_PATH }}/*

  CLI:
    runs-on: ubuntu-latest
    name: CLI
    needs: [deleteOldReleases]
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Copiler
      uses: Sirherobrine23/Actions-Build-Openwrt@main
      with:
        CONFIG: 'configs/cli.config'
        BRANCH: 'openwrt-19.07'
        P1: 'p1.sh'
        P2: 'p2.sh'
        NGROK_TOKEN: "${{ secrets.NGROK_AUTH }}"

    - name: Upload To Releases
      uses: softprops/action-gh-release@v1
      if: env.UPLOADTORELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Build to ${{ env.DEVICE_NAME }}, Run ID ${{ github.run_id }}
        tag_name: ${{ github.run_id }}-CLI
        body_path: ${{ env.BODY_PATH }}
        files: ${{ env.FIRMWARE_PATH }}/*
