name: OpenWRT Github CI
on:
  push:
  watch:
    types: started
  schedule:
    - cron: "55 12 */4 * */5"

jobs:
  Clean:
    runs-on: ubuntu-latest
    name: Remove Old releases
    steps:
    - name: Delete releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        keep_latest: 2
        delete_tags: true

  OpenwrtBuild:
    runs-on: ubuntu-latest
    name: "Config: ${{ matrix.configFile }}, Branch/Tag: ${{ matrix.branch }}"
    needs:
      - Clean 
    strategy:
      matrix:
        branch:
          - v18.06.9
          - openwrt-19.07
        configFile:
          - adblock
          - cli
          - luci
          - wireguard-luci
          - wireguard-cli
    
    # Build steps
    steps:
      - name: Checkout Reposiory
        uses: actions/checkout@main

      - name: "Build, CONFIG: ${{ matrix.configFile }}, and Branch: ${{ matrix.branch }}"
        uses: Sirherobrine23/Actions-Build-Openwrt@main
        continue-on-error: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          CONFIG: "configs/${{ matrix.configFile }}.config"
          BRANCH: "${{ matrix.branch }}"
          BASENAME: "WR941NDV3_${{ matrix.branch }}_${{ matrix.configFile }}"
          RELEASE: true
          RELEASE_TAGNAME: "CI_v${{ github.run_id }}"
          RELEASE_BODY: |
            Device: TP-Link WR941ND (v3)
          # Fist script before clone repo
          SCRIPT1: |
            #!/bin/bash
            # Modify default IP
            # sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
            ConfigGen="package/base-files/files/bin/config_generate"
            # Hostaname
            cat "${ConfigGen}" | sed 's|OpenWrt|wr941ndv3|g' | sed 's|0.openwrt.pool.ntp.org|a.st1.ntp.br|g' | sed 's|1.openwrt.pool.ntp.org|b.st1.ntp.br|g' | sed 's|2.openwrt.pool.ntp.org|c.st1.ntp.br|g' | sed 's|3.openwrt.pool.ntp.org|d.st1.ntp.br|g' | tee "${ConfigGen}"

            # OpenWRT Wireless Activated
            WirelessFile="package/kernel/mac80211/files/lib/wifi/mac80211.sh"
            cat "${WirelessFile}" | sed 's|wireless.radio${devidx}.disabled=1|wireless.radio${devidx}.disabled=0|g' | sed 's|wireless.default_radio${devidx}.ssid=OpenWrt|wireless.default_radio${devidx}.ssid=OpenWrt-WR941NDv3|g' | tee "${WirelessFile}"
