name: OpenWRT Github CI
on:
  push:
  watch:
    types: started
  schedule:
    - cron: 0 0 * * */3

jobs:
  OpenwrtBuild:
    runs-on: ubuntu-latest
    name: "Branch: ${{ matrix.branch }}, Config: ${{ matrix.config }}"
    strategy:
      matrix:
        branch:
          - openwrt-19.07
          - openwrt-18.06
        configFile:
          - adblock
          - cli
          - luci
          - wireguard-luci
          - wireguard-cli
    
    # Build steps
    steps:
      - name: Checkout Reposiory
        uses: actions/checkout@main

      - name: "Build, CONFIG: ${{ matrix.configFile }}, and Branch: ${{ matrix.branch }}"
        uses: Sirherobrine23/Actions-Build-Openwrt@main
        continue-on-error: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          CONFIG: "configs/${{ matrix.configFile }}.config"
          BRANCH: "${{ matrix.branch }}"
          BASENAME: "WR941NDV3_${{ matrix.branch }}_${{ matrix.configFile }}"
          RELEASE: true
          RELEASE_TAGNAME: "${{ github.run_id }}"
          RELEASE_BODY: |
            Branch: ${{ matrix.branch }}
            Config File: ${{ matrix.configFile }}
            Device: TP-Link WR941ND (v3)
          SCRIPT2: |
            #!/bin/Bash
            pwd
            find bin/ -type f
            sudo bash -c 'apt update && apt install -y tree's
            tree bin/
          # Fist script before clone repo
          SCRIPT1: |
            #!/bin/bash
            # Modify default IP
            # sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate

            # Hostaname
            sed -i 's/OpenWrt/wr941ndv3/g' "package/base-files/files/bin/config_generate"

            # NTP Server Brazil
            sed -i 's/0.openwrt.pool.ntp.org/a.st1.ntp.br/g' "package/base-files/files/bin/config_generate"
            sed -i 's/1.openwrt.pool.ntp.org/b.st1.ntp.br/g' "package/base-files/files/bin/config_generate"
            sed -i 's/2.openwrt.pool.ntp.org/c.st1.ntp.br/g' "package/base-files/files/bin/config_generate"
            sed -i 's/3.openwrt.pool.ntp.org/d.st1.ntp.br/g' "package/base-files/files/bin/config_generate"

            # OpenWRT Wireless Activated
            sed -i 's/set wireless.radio${devidx}.disabled=1/set wireless.radio${devidx}.disabled=0/g' "package/kernel/mac80211/files/lib/wifi/mac80211.sh"
            sed -i 's/set wireless.default_radio${devidx}.ssid=OpenWrt/set wireless.default_radio${devidx}.ssid=Openwrt-WR941NDv3/g' "package/kernel/mac80211/files/lib/wifi/mac80211.sh"

      # Remove files
      - name: remove files
        run: sudo rm -rfv openwrt/build_dir/

      - name: Upload debian package file
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.branch }}_${{ matrix.configFile }}"
          path: "./"
