name: OpenWRT Github CI
on:
  push:
  watch:
    types: started
  schedule:
    - cron: 0 0 * * */3

jobs:
  deleteOldReleases:
    runs-on: ubuntu-latest
    name: Delete old releases
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Delete Old Releases
      uses: Sirherobrine23/delete-older-releases@master
      continue-on-error: true
      with:
        delete_tags: true
        keep_latest: 1
        pattern_regex: true
        delete_tag_pattern: "Build_.*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - adblock
          - cli
          - luci
          - wireguard-with-luci
          - wireguard-without-luci
        branch:
          # - openwrt-19.07
          - openwrt-18.06
    needs: [deleteOldReleases]
    name: "Branch: ${{ matrix.branch }}, Config: ${{ matrix.config }}"
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Copiler
      uses: Sirherobrine23/Actions-Build-Openwrt@main
      # continue-on-error: true
      with:
        config: "configs/${{ matrix.config }}.config"
        branch: "{{ matrix.branch }}"
        p1: 'p1.sh'
        p2: 'p2.sh'

    - name: Upload To Releases
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: "TP-Link WR941NDv3, Run ID: ${{ github.run_id }}, Branch: {{ matrix.branch }}"
        tag_name: "Build_${{ github.run_id }}_{{ matrix.branch }}"
        files: "*.bin"
